import {load60,payables60View} from './v60-ui.js';
import {load55,v55} from './v55-ui.js';
import {FREIGHT_NAMES,freightFamilies} from './v51-domain.js';
import {filteredProjects,v51} from './v51-ui.js';
import { ROLE_LABELS, permitted, mergeConfig, monthlyDashboard, monthInChile, calculateFreight, taxonomyPaths } from './v5-domain.js';
import { IMPORT_FIELDS, readImportWorkbook, parseText, suggestMapping, parseMappedRows, colLabel, transpose, normalized } from './v5-import.js';

const h=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=v=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v)||0);
const qty=v=>new Intl.NumberFormat('es-CL',{maximumFractionDigits:2}).format(Number(v)||0);
const opt=(value,label,selected)=>`<option value="${h(value)}" ${String(value)===String(selected)?'selected':''}>${h(label)}</option>`;
const btn=(action,label,extra='',className='secondary')=>`<button type="button" class="${className}" data-v5="${action}" ${extra}>${label}</button>`;
const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${h(value)}" ${extra}></label>`;
const grainChoices={longitudinal:'Longitudinal',transversal:'Transversal','sin-veta':'Sin veta'};
const familyNames=FREIGHT_NAMES;
const finishes={rough:'Solo lineal',bevel:'Biselado / Pulido',miter45:'45°'};
export const v5={config:mergeConfig(),month:monthInChile(new Date()),dispatches:[],dashboard:null,dispatchEdit:null,productEdit:null,productKind:'board',catalogSearch:'',revisions:null,groupsFilter:'',importer:null};
function freshImporter(ctx){return {fileName:'',sheets:[],sheetIndex:0,text:'',config:{mapping:{},units:'mm',headerRow:1,startRow:2,endRow:'',materialId:ctx.state.materialId||'',defaultGrain:'longitudinal',defaultType:'',workType:ctx.state.workType,
  blankIsNone:true,markerMap:{x:'selected'},countMap:{'1':1,'2':2},typeMap:{},materialMap:{},grainMap:{l:'longitudinal',t:'transversal',sv:'sin-veta',longitudinal:'longitudinal',transversal:'transversal','sin veta':'sin-veta'},measurementMode:'finished'},preview:null,templates:readTemplates()};}
function readTemplates(){try{return JSON.parse(localStorage.getItem('casa-v5-import-templates')||'{}');}catch{return {};}}
function currentRows(I){return I.sheets[I.sheetIndex]?.rows||[];}
function types(ctx,selected,includeEmpty=true){return (includeEmpty?opt('','Seleccionar',selected):'')+(ctx.state.workType==='slabs'?Object.entries(finishes).map(([k,n])=>opt(k,n,selected)).join(''):ctx.edges.filter(e=>e.active!==false).map(e=>opt(e.id,`${e.sku} · ${e.name} · ${e.thickness} mm`,selected)).join(''));}
function cols(I,selected){const rows=I.config.transpose?transpose(currentRows(I)):currentRows(I),headers=rows[Number(I.config.headerRow)-1]||[];return opt('','No viene en el archivo',selected)+Array.from({length:Math.max(0,...rows.map(r=>r.length))},(_,i)=>opt(i,`${colLabel(i)} · ${String(headers[i]??'').slice(0,60)}`,selected)).join('');}
function uniqueColumn(I,field){const c=I.config.mapping[field];if(c===''||c===undefined)return [];const rows=I.config.transpose?transpose(currentRows(I)):currentRows(I);return [...new Set(rows.slice(Number(I.config.startRow)-1,Number(I.config.endRow)||undefined).map(r=>normalized(r[c])).filter(Boolean))].slice(0,150);}

export function importerView(ctx) {
  const I=v5.importer||=freshImporter(ctx),c=I.config;c.workType=ctx.state.workType;
  const rows=c.transpose?transpose(currentRows(I)):currentRows(I);
  const mappingRow=(key,label)=>`<label>${label}<select data-v5-map="${key}">${cols(I,c.mapping[key]??'')}</select></label>`;
  const dictionary=(field,dict,label,options)=>{const tokens=uniqueColumn(I,field);return tokens.length?`<h4>${label}</h4><div class="v5-grid">${tokens.map(token=>`<label>${h(token)}<select data-v5-dict="${dict}" data-token="${h(token)}">${options(c[dict]?.[token]||'')}</select></label>`).join('')}</div>`:'';};
  const sourcePreview=rows.slice(Math.max(0,Number(c.headerRow)-1),Math.max(0,Number(c.headerRow)-1)+6);
  return `<section class="v5-import card"><div class="section-title"><div><h3>Importar o pegar desde Excel</h3><p>Asigna el significado de cada columna. Largo y Ancho conservan sus ejes aunque Largo sea menor.</p></div><span class="v5-badge">XLS · XLSX · CSV · pegado</span></div>
    <div class="v5-grid"><label>Archivo del cliente<input type="file" accept=".xls,.xlsx,.csv,.tsv,.ods" data-v5-file></label><label>O copia las celdas aquí<textarea data-v5-text rows="3" placeholder="Pega filas y columnas, con o sin encabezados">${h(I.text)}</textarea></label></div>
    ${btn('read-paste','Leer celdas pegadas')}
    ${I.sheets.length?`<hr><div class="v5-grid"><label>Hoja<select data-v5-import="sheetIndex">${I.sheets.map((s,i)=>opt(i,s.name,I.sheetIndex)).join('')}</select></label><label>Unidad de todo este bloque<select data-v5-import="units">${opt('mm','Milímetros (mm)',c.units)}${opt('cm','Centímetros (cm) → ×10',c.units)}</select></label><label>Fila de encabezados<input type="number" min="1" data-v5-import="headerRow" value="${c.headerRow}"></label><label>Primera fila de datos<input type="number" min="1" data-v5-import="startRow" value="${c.startRow}"></label><label>Última fila de datos<input type="number" min="1" placeholder="${rows.length}" data-v5-import="endRow" value="${c.endRow}"></label><label>Omitir filas (ej. 10,20)<input data-v5-import="skipRows" value="${h(c.skipRows||'')}"></label></div>
    <label class="checkbox-row"><input type="checkbox" data-v5-import="transpose" ${c.transpose?'checked':''}> Los campos están en filas: transponer el bloque</label>
    <div class="v5-scroll"><table><thead><tr>${Array.from({length:Math.max(0,...rows.map(r=>r.length))},(_,i)=>`<th>${colLabel(i)}</th>`).join('')}</tr></thead><tbody>${sourcePreview.map((row,i)=>`<tr>${row.map(cell=>`<td>${h(String(cell).slice(0,65))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
    <div class="v5-actions">${btn('suggest-mapping','Sugerir columnas desde encabezados')}<label>Plantilla guardada<select data-v5-template><option value="">Elegir…</option>${Object.keys(I.templates).map(n=>opt(n,n,'')).join('')}</select></label>${btn('save-template','Guardar interpretación')}</div>
    <h4>Qué significa cada columna</h4><div class="v5-grid">${Object.entries(IMPORT_FIELDS).map(([k,n])=>mappingRow(k,n)).join('')}</div>
    <h4>Valores comunes cuando faltan columnas</h4><div class="v5-grid"><label>Material<select data-v5-import="materialId">${opt('','Seleccionar',c.materialId)}${ctx.selectedMaterials().map(m=>opt(m.id,`${m.sku} · ${m.name}`,c.materialId)).join('')}</select></label><label>Veta<select data-v5-import="defaultGrain">${Object.entries(grainChoices).map(([k,n])=>opt(k,n,c.defaultGrain)).join('')}</select></label><label>${ctx.state.workType==='slabs'?'Servicio seleccionado':'Tapacanto seleccionado'}<select data-v5-import="defaultType">${types(ctx,c.defaultType)}</select></label><label>Medidas<select data-v5-import="measurementMode">${opt('finished','Terminadas · descontar espesor de canto',c.measurementMode)}${opt('cut','De corte · ya descontadas',c.measurementMode)}</select></label></div>
    ${dictionary('material','materialMap','Relacionar materiales del cliente',selected=>opt('','Seleccionar',selected)+ctx.selectedMaterials().map(m=>opt(m.id,`${m.sku} · ${m.name}`,selected)).join(''))}
    ${dictionary('edgeType','typeMap','Relacionar tipos o códigos',selected=>types(ctx,selected))}
    ${dictionary('grain','grainMap','Interpretación de la veta',selected=>opt('','Seleccionar',selected)+Object.entries(grainChoices).map(([k,n])=>opt(k,n,selected)).join(''))}
    <h4>Símbolos por lado</h4><p>L1 / L2 tienen la medida Largo; A1 / A2 tienen la medida Ancho. Se mantienen al rotar la pieza en el plano.</p>
    <div class="v5-grid">${[...new Set(['x',...Object.keys(c.markerMap),...['top','bottom','left','right'].flatMap(k=>uniqueColumn(I,k)).filter(t=>t!=='0'&&!(c.numericPresence&&Number(t)>0))])].slice(0,150).map(token=>`<label>«${h(token)}» significa<select data-v5-dict="markerMap" data-token="${h(token)}">${opt('','Por definir',c.markerMap[token])}${opt('none',ctx.state.workType==='slabs'?'Solo lineal':'Sin tapacanto',c.markerMap[token])}${opt('selected','Usar tipo seleccionado / columna tipo',c.markerMap[token])}${types(ctx,c.markerMap[token],false)}</select></label>`).join('')}</div>
    <label class="checkbox-row"><input type="checkbox" data-v5-import="blankIsNone" ${c.blankIsNone?'checked':''}> 0 y celda vacía = ${ctx.state.workType==='slabs'?'solo corte lineal':'sin tapacanto'}</label>
    <label class="checkbox-row"><input type="checkbox" data-v5-import="numericPresence" ${c.numericPresence?'checked':''}> Números positivos en columnas de lados son longitudes marcadas: usar el tipo seleccionado</label>
    ${['longEdges','shortEdges'].some(k=>c.mapping[k]!==undefined&&c.mapping[k]!=='')?`<h4>Columnas con cantidad de lados</h4><div class="v5-grid">${[...new Set(['1','2',...uniqueColumn(I,'longEdges'),...uniqueColumn(I,'shortEdges')])].map(token=>`<label>«${h(token)}»<select data-v5-dict="countMap" data-token="${h(token)}">${opt('','Por definir',c.countMap[token])}${[0,1,2].map(n=>opt(n,`${n} lado(s)`,c.countMap[token])).join('')}</select></label>`).join('')}</div><p>Un lado corresponde a L1 o A1; dos, a ambos lados del eje. Corrige lados individuales en la revisión.</p>`:''}
    <label class="checkbox-row"><input type="checkbox" data-v5-import="allowTypeWithoutSides" ${c.allowTypeWithoutSides?'checked':''}> Confirmo que las filas con tipo pero sin lados deben quedar sin servicio de borde</label>
    ${btn('preview-import','Validar e interpretar','', 'primary')}
    ${I.preview?`<div class="v5-preview"><h4>${I.preview.pieces.length} filas válidas · ${I.preview.totalUnits||0} unidades · ${I.preview.issues.length} filas por revisar</h4>${I.preview.issues.length?`<div class="alert">${I.preview.issues.slice(0,30).map(e=>`Fila ${e.row}: ${h(e.message)}`).join('<br>')}${I.preview.issues.length>30?'<br>Hay más errores; corrige el bloque o excluye filas.':''}</div>`:''}
      <div class="v5-scroll"><table><thead><tr><th>Fila</th><th>Pieza</th><th>Largo mm</th><th>Ancho mm</th><th>Cant.</th><th>Veta</th><th>L1</th><th>L2</th><th>A1</th><th>A2</th></tr></thead><tbody>${I.preview.pieces.map((p,i)=>`<tr><td>${p.sourceRow}</td><td>${h(p.name)}</td>${['length','width','quantity'].map(f=>`<td><input type="number" min="1" data-v5-preview="${i}" data-field="${f}" value="${p[f]}"></td>`).join('')}<td><select data-v5-preview="${i}" data-field="grain">${Object.entries(grainChoices).map(([k,n])=>opt(k,n,p.grain)).join('')}</select></td>${['top','bottom','left','right'].map(side=>`<td><select data-v5-preview="${i}" data-field="${side}">${opt('',ctx.state.workType==='slabs'?'Lineal':'Sin canto','')}${types(ctx,ctx.state.workType==='slabs'?p.finishes[side]:p.edges[side],false)}</select></td>`).join('')}</tr>`).join('')}</tbody></table></div>
      ${btn('confirm-import','Incorporar bloque revisado',I.preview.issues.length||!I.preview.pieces.length?'disabled':'','primary')}<p>Para planos con varios bloques, incorpora uno y luego cambia las columnas o el rango del siguiente.</p></div>`:''}`:'<p>El archivo se lee en este navegador. No se modifica la planilla original.</p>'}
  </section>`;
}

export function dashboardView(ctx) {
  const report=permitted(ctx.user,'reports'),d=v5.dashboard||monthlyDashboard(ctx.projects,v5.month,v5.config.salesBasis,v5.dispatches);
  const bars=(values)=>{const entries=Object.entries(values),max=Math.max(1,...Object.values(values));return entries.length?entries.map(([name,value])=>`<div class="v5-bar-row"><div><span>${h(name)}</span><b>${money(value)}</b></div><div class="v5-bar-track"><span style="width:${value/max*100}%"></span></div></div>`).join(''):'<p class="v5-muted">Sin ventas registradas en este mes.</p>';};
  return `<div class="v5-welcome"><div><p class="eyebrow">CASA DISEÑO · MULTIESPACIO</p><h2>Panel general</h2><p>Hola, ${h(ctx.user?.fullName||'Visitante')}. Tus proyectos y áreas de trabajo en un solo lugar.</p></div>${report?`<label>Mes del informe<input type="month" data-v5-month value="${v5.month}"></label>`:''}</div>
  <div class="v5-module-grid">${[['boards','Tableros','Maderas, piezas y tapacantos','▤'],['slabs','Placas','Piedras y terminaciones','◆'],['dispatch','Despachos','Direcciones, fletes y entregas','↗']].map(([key,title,desc,icon])=>`<button class="v5-module" data-v5="module" data-module="${key}"><span>${icon}</span><h3>${title}</h3><p>${desc}</p><b>Ingresar →</b></button>`).join('')}</div>
  ${report?`<div class="v5-report-heading"><h3>Resumen mensual</h3><p>Venta neta al estado <b>${v5.config.salesBasis==='facturacion'?'Facturación':'Facturado y pagado'}</b>. Producción al primer ingreso a Despacho.</p></div><div class="v5-kpis">${[['Venta neta',money(d.netSales)],['Tableros cortados',qty(d.boards)],['Placas cortadas',qty(d.slabs)],['Tapacanto instalado',qty(d.edgeMeters)+' ml'],['Biselados / pulidos',qty(d.bevelMeters)+' ml'],['Corte 45°',qty(d.miter45Meters)+' ml']].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join('')}</div><div class="v5-chart-grid"><section class="card"><h3>Venta neta por comercial</h3>${bars(d.sales)}</section><section class="card"><h3>Venta neta por familia</h3>${bars(d.families)}</section></div>${d.undatedProduction||d.undatedSales?`<div class="alert">Historial anterior sin fecha de hito: ${d.undatedSales} ventas y ${d.undatedProduction} pedidos de producción. Se conservan y se excluyen de este informe mensual para no inventar fechas.</div>`:''}`:'<section class="card"><h3>Mis proyectos</h3><p>Consulta tus cotizaciones, sus planos y su estado.</p>'+btn('projects','Ver proyectos')+'</section>'}
  ${payables60View(ctx)}<section class="v5-coming"><h3>Próximamente</h3><div>${['Amoblamiento','Remodelación','Otros'].map(n=>`<span>${n}<small>Próximamente</small></span>`).join('')}</div></section>`;
}
export function groupedProjectsView(ctx) {
  const groups=new Map();for(const p of filteredProjects(ctx.projects)){const id=p.groupId||p.id;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(p);}
  return `<div class="intro-row"><div><h2>Proyectos y cotizaciones</h2><p>Un proyecto reúne cotizaciones independientes de Tableros y Placas. Cada una conserva su historial.</p></div>${ctx.canCreateQuote()?btn('new-group','Nuevo proyecto','','primary'):''}</div>
  ${[...groups].map(([id,quotes])=>`<section class="card v5-project"><header><div><h3>${h(quotes[0].project.projectName||'Proyecto sin nombre')}</h3><p>${h(quotes[0].project.clientName)}</p></div><div class="v5-actions">${ctx.canCreateQuote()?btn('add-quote','＋ Cotización',`data-id="${h(id)}"`):''}${btn('group-dispatch','Despachos',`data-id="${h(id)}"`)}</div></header><div class="v5-scroll"><table><thead><tr><th>Cotización</th><th>Revisión</th><th>Estado</th><th>Venta neta</th><th></th></tr></thead><tbody>${quotes.map(p=>`<tr><td><b>${h(p.quoteName||(p.workType==='slabs'?'Placas':'Tableros'))}</b><small class="v5-muted">${h(p.id.slice(0,8).toUpperCase())} · ${h(p.assignedName||p.ownerName||'Sin comercial')}</small></td><td>R${p.revisionNo||1} · ${h(p.settings?.calculationVersion||'V3')}</td><td><select data-project-status="${p.id}" ${ctx.canEditRecord(p)?'':'disabled'}>${ctx.statusEntries(p.project.status).map(([v,n])=>opt(v,n,p.project.status)).join('')}</select></td><td>${money(p.summary?.net)}</td><td><div class="v5-actions">${btn('open-quote','Abrir',`data-id="${p.id}"`)}${btn('revisions','Historial',`data-id="${p.id}"`)}${permitted(ctx.user,'resources')||permitted(ctx.user,'costs')?`<button type="button" class="secondary" data-v55="costs" data-id="${p.id}">Costos</button>`:''}</div></td></tr>`).join('')}</tbody></table></div></section>`).join('')||'<section class="card"><p>Aún no hay proyectos.</p></section>'}
  ${v5.revisions?`<section class="card"><h3>Historial de cotización</h3><p>Cada cálculo queda disponible para consulta y descarga.</p>${v5.revisions.map((r,i)=>`<div class="v5-history-row"><span>R${r.revisionNo||1} · ${h(r.settings?.calculationVersion||'V3')} · ${money(r.summary?.net)} neto</span>${btn('open-revision','Consultar',`data-index="${i}"`)}</div>`).join('')}</section>`:''}`;
}
export function dispatchView(ctx) {
  const d=v5.dispatchEdit||{},groups=[...new Map(ctx.projects.map(p=>[p.groupId||p.id,p])).entries()];
  const quote=d.groupId?calculateFreight(v5.config,d.communeId,d.families||[]):null;
  return `<div class="intro-row"><div><h2>Despachos</h2><p>Flete neto de ida desde ${h(v5.config.origin.address)}. Distancia por carretera al centro de la comuna.</p></div><a class="secondary" href="${h(v5.config.origin.mapsUrl)}" target="_blank" rel="noopener">Ver origen ↗</a></div>
  ${permitted(ctx.user,'dispatch')?`<form data-v5-form="dispatch" class="card"><h3>${d.id?'Editar':'Cotizar'} despacho</h3><div class="v5-grid"><label>Proyecto<select name="groupId" required data-v5-dispatch="groupId"><option value="">Seleccionar</option>${groups.map(([id,p])=>opt(id,`${p.project.projectName||'Sin nombre'} · ${p.project.clientName}`,d.groupId)).join('')}</select></label>${field('street','Calle y número',d.street,'text','required data-v5-dispatch="street"')}<label>Comuna<select name="communeId" required data-v5-dispatch="communeId"><option value="">Seleccionar</option>${v5.config.communes.filter(c=>c.active!==false).map(c=>opt(c.id,c.name,d.communeId)).join('')}</select></label>${field('date','Fecha programada',d.date,'date')}<label>Estado<select name="status">${Object.entries({pending:'Por programar',scheduled:'Programado',dispatched:'En despacho',delivered:'Entregado',cancelled:'Anulado'}).map(([k,n])=>opt(k,n,d.status||'pending')).join('')}</select></label>${field('invoiceNumber','Factura de flete (opcional)',d.invoiceNumber)}${field('invoiceDate','Fecha de factura de flete',d.invoiceDate,'date')}</div>
  <div class="v5-actions">${Object.entries(familyNames).map(([key,name])=>`<label class="checkbox-row"><input type="checkbox" name="family" value="${key}" data-v5-family ${d.families?.includes(key)?'checked':''}>${name}</label>`).join('')}</div>
  <p class="v5-freight-value">${quote?.net!=null?`${money(quote.net)} neto · ${quote.roadKm} km · tarifa ${familyNames[quote.family]}`:'Por cotizar · selecciona comuna con distancia verificada'}</p>
  <p>En un envío mixto se aplica el mayor valor calculado; no se suman las categorías.</p>${field('notes','Observaciones',d.notes)}<button class="primary" type="submit">Guardar despacho</button> ${btn('new-dispatch','Limpiar formulario')}</form>`:'<p>Tu perfil permite consultar el seguimiento de los despachos disponibles.</p>'}
  ${!v5.config.communes.length?`<div class="alert">El superadministrador debe agregar las comunas y sus kilómetros verificados en Configuración → Despachos.</div>`:''}
  <section class="card"><h3>Seguimiento</h3><div class="v5-scroll"><table><thead><tr><th>Proyecto / cliente</th><th>Destino</th><th>Estado</th><th>Neto</th><th></th></tr></thead><tbody>${v5.dispatches.map(x=>`<tr><td>${h(x.projectName)}<small class="v5-muted">${h(x.clientName)}</small></td><td>${h(x.street)} · ${h(x.quote.commune||v5.config.communes.find(c=>c.id===x.communeId)?.name||'')}<small class="v5-muted">${x.quote.roadKm??'—'} km · ${h(x.date)}</small></td><td>${h({pending:'Por programar',scheduled:'Programado',dispatched:'En despacho',delivered:'Entregado',cancelled:'Anulado'}[x.status])}</td><td>${x.quote.net==null?'Por cotizar':money(x.quote.net)}</td><td>${permitted(ctx.user,'dispatch')?btn('edit-dispatch','Abrir',`data-id="${x.id}"`):''}<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.street+', '+(x.quote.commune||'Chile'))}" target="_blank" rel="noopener">Ver destino ↗</a></td></tr>`).join('')}</tbody></table></div></section>`;
}

export function configurationView(ctx) {
 const config=v5.config,admin=permitted(ctx.user,'settings');
 return `<h2>Configuración</h2>${admin?`<p><button type="button" class="primary" data-v55="parameters">Comunas, pesos, rendimientos y relaciones Salice</button></p><form class="card" data-v5-form="settings"><h3>Parámetros generales</h3><div class="v5-grid">${field('defaultKerf','Consumo de disco predeterminado (mm)',config.defaultKerf??3,'number','min="2" max="5" step="0.1" required')}${field('originLabel','Nombre del origen',config.origin.label)}${field('originAddress','Dirección de origen',config.origin.address)}${field('originMaps','Enlace Google Maps',config.origin.mapsUrl,'url')}<label>Ventas del panel<select name="salesBasis">${opt('facturado_pagado','Facturado y pagado',config.salesBasis)}${opt('facturacion','Ingresado a Facturación',config.salesBasis)}</select></label></div><button class="primary">Guardar configuración</button></form>`:''}
 ${permitted(ctx.user,'catalog')?`<section class="card"><h3>Productos, dimensiones y servicios</h3><p>Edita medidas por producto o selecciona una categoría para aplicar dimensiones en bloque. Los servicios se administran con su código y precio neto.</p><button class="primary" data-v51="dimensions">Administrar catálogo y dimensiones</button></section>`:''}
 ${permitted(ctx.user,'categories')?`<section class="card"><h3>Categorías y subcategorías</h3><form class="v5-grid" data-v5-form="taxonomy">${field('id','Código (vacío para crear)')}${field('name','Nombre','','text','required')}<label>Categoría padre<select name="parentId"><option value="">Categoría principal</option>${taxonomyPaths(config.taxonomy).map(n=>opt(n.id,n.path,'')).join('')}</select></label><label>Familia<select name="family">${Object.entries(familyNames).map(([k,n])=>opt(k,n,'boards')).join('')}</select></label><label>Estado<select name="active"><option value="true">Activo</option><option value="false">Inactivo</option></select></label><button class="primary">Crear / actualizar</button></form><table><thead><tr><th>Código</th><th>Jerarquía</th><th>Estado</th></tr></thead><tbody>${taxonomyPaths(config.taxonomy).map(n=>`<tr><td>${h(n.id)}</td><td>${h(n.path)}</td><td>${n.active===false?'Inactivo':'Activo'}</td></tr>`).join('')}</tbody></table></section>`:''}`;
}

export function catalogManagementView(ctx) {
 const kind=v5.productKind,board=kind==='board',accessory=kind==='accessory',items=board?ctx.materials:accessory?ctx.accessories:ctx.edges,p=v5.productEdit||{},costs=permitted(ctx.user,'costs'),sales=permitted(ctx.user,'salesPrices'),products=permitted(ctx.user,'products');
 const number=(key,label)=>field(key,label,p[key]??0,'number','min="0" step="0.01"');
 const disabled=products?'':'disabled';
 return `<div class="intro-row"><div><h2>Gestión de catálogo</h2><p>Editar crea una revisión del producto. Las cotizaciones anteriores conservan la referencia original.</p></div>${btn('new-product','Nuevo producto')}</div><div class="v5-actions">${btn('catalog-kind','Tableros y placas','data-kind="board"',board?'primary':'secondary')}${btn('catalog-kind','Tapacantos','data-kind="edge"',kind==='edge'?'primary':'secondary')}${btn('catalog-kind','Herrajes / futuros','data-kind="accessory"',accessory?'primary':'secondary')}${btn('settings','Categorías y servicios')}</div>
 <form class="card" data-v5-form="product"><h3>${p.id?'Editar '+h(p.sku):'Nuevo producto'}</h3><fieldset ${disabled}><div class="v5-grid">${field('sku','Código',p.sku,'text','required')}${field('name','Nombre',p.name,'text','required')}${field('supplier','Proveedor',p.supplier)}${field('supplierCode','Código proveedor',p.supplierCode)}${field('stock','Stock (vacío: no informado)',p.stock??'','number','min="0" step="0.01"')}${field('colorName','Color',p.colorName)}${field('format','Formato / presentación',p.format)}<label>Categoría<select name="taxonomyId"><option value="">Sin asignar</option>${taxonomyPaths(v5.config.taxonomy).map(n=>opt(n.id,n.path,p.taxonomyId)).join('')}</select></label><label>Activo<select name="active">${opt('true','Activo',String(p.active!==false))}${opt('false','Inactivo',String(p.active!==false))}</select></label>
 ${accessory?`${number('plateLength','Largo / formato (mm)')}${number('plateWidth','Ancho / formato (mm)')}${number('thickness','Espesor (mm)')}`:board?`${field('brand','Marca',p.brand||'Sin marca')}<label>Tipo de material<select name="materialType">${opt('board','Tablero de madera',p.materialType||'board')}${opt('neolith','Neolith',p.materialType)}${opt('stone','Otra piedra',p.materialType)}</select></label>${number('plateLength','Largo de fábrica (mm)')}${number('plateWidth','Ancho de fábrica (mm)')}${number('thickness','Espesor (mm)')}<small>Rebaje V5: 10 mm por lado en madera y 30 mm en piedra.</small><label>Veta<select name="grainRequired">${opt('true','Con veta',String(p.grainRequired!==false))}${opt('false','Sin veta',String(p.grainRequired!==false))}</select></label>`:`${field('group','Grupo',p.group||'PVC')}${field('material','Material',p.material||'PVC')}${number('thickness','Espesor (mm)')}${field('color','Color de referencia',p.color||'#334155','color')}`}
 </div></fieldset><div class="v5-grid">${sales?((board||accessory)?number('netPrice','Venta neta por tablero'):number('price','Venta neta por ml')+number('serviceRate','Instalación neta por ml')):''}${costs?number('purchasePrice','Costo compra')+number('minPrice','Precio mínimo venta')+(kind==='edge'?number('servicePurchasePrice','Costo instalación/ml')+number('serviceMinPrice','Mínimo instalación/ml'):''):''}</div><label>Fotografía<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" ${disabled}></label><label>Descripción<textarea name="description" ${disabled}>${h(p.description)}</textarea></label><button class="primary">Guardar revisión de producto</button></form>
 <section class="card"><label>Buscar por código o nombre<input data-v5-catalog-search value="${h(v5.catalogSearch)}"></label><div class="v5-scroll"><table><thead><tr><th>Código / producto</th><th>Formato</th><th>Venta neta</th><th>Estado</th><th></th></tr></thead><tbody>${items.filter(x=>!items.some(y=>y.replacesId===x.id)).filter(x=>normalized(x.sku+' '+x.name).includes(normalized(v5.catalogSearch))).slice(0,150).map(x=>`<tr><td><b>${h(x.sku)}</b><small class="v5-muted">${h(x.name)}</small></td><td>${board?`${x.plateLength} × ${x.plateWidth} × ${x.thickness}`:x.thickness+' mm'}</td><td>${money(x.netPrice??x.price)}</td><td>${x.active===false?'Inactivo':'Activo'}</td><td>${btn('edit-product','Editar',`data-id="${x.id}"`)}</td></tr>`).join('')}</tbody></table></div><p>Se muestran hasta 150 resultados. Usa el buscador para localizar un producto.</p></section>`;
}

export async function loadV5(ctx) {
 await load55(ctx);
 v5.config=mergeConfig(await ctx.api(ctx.user?'/api/v5/config':'/api/v5/public-config'));
 if(ctx.user){v5.dispatches=(await ctx.api('/api/v5/dispatches')).dispatches||[];if(permitted(ctx.user,'reports'))v5.dashboard=await ctx.api(`/api/v5/dashboard?month=${v5.month}`);}
 else {v5.dispatches=[];v5.dashboard=null;}
 await load60(ctx);
}
export function attachV5(app,getContext) {
 const run=fn=>async event=>{try{await fn(event,getContext());}catch(error){getContext().notify(error.message,'error');}};
 app.addEventListener('input',event=>{const t=event.target;if(t.matches('[data-v5-text]'))(v5.importer||={}).text=t.value;});
 app.addEventListener('change',run(async(event,ctx)=>{
   const t=event.target,I=v5.importer;
   if(t.matches('[data-v5-file]')){const file=t.files?.[0];if(!file)return;if(file.size>12*1024*1024)throw new Error('Archivo demasiado grande. Divide los bloques o pega sus celdas.');const next=freshImporter(ctx);next.fileName=file.name;next.sheets=readImportWorkbook(await file.arrayBuffer());next.config.mapping=suggestMapping(next.sheets[0].rows,1);v5.importer=next;ctx.render();return;}
   if(t.dataset.v5Import){const key=t.dataset.v5Import;I.preview=null;if(key==='sheetIndex'){I.sheetIndex=Number(t.value);I.config.mapping={};}else I.config[key]=t.type==='checkbox'?t.checked:t.value;ctx.render();}
   if(t.dataset.v5Map){I.config.mapping[t.dataset.v5Map]=t.value===''?'':Number(t.value);I.preview=null;ctx.render();}
   if(t.dataset.v5Dict){I.config[t.dataset.v5Dict][t.dataset.token]=t.value;I.preview=null;ctx.render();}
   if(t.matches('[data-v5-template]')&&t.value){I.config=structuredClone(I.templates[t.value]);I.preview=null;ctx.render();}
   if(t.dataset.v5Preview!==undefined){const p=I.preview.pieces[Number(t.dataset.v5Preview)],f=t.dataset.field;if(['length','width','quantity'].includes(f))p[f]=Number(t.value);else if(f==='grain')p.grain=t.value;else if(ctx.state.workType==='slabs')p.finishes[f]=t.value||'rough';else p.edges[f]=t.value||null;}
   if(t.matches('[data-v5-month]')){v5.month=t.value;await loadV5(ctx);ctx.render();}
   if(t.dataset.v5Dispatch){(v5.dispatchEdit||={})[t.dataset.v5Dispatch]=t.value;if(t.dataset.v5Dispatch==='groupId'){const qs=ctx.projects.filter(p=>(p.groupId||p.id)===t.value);v5.dispatchEdit.families=freightFamilies(qs,ctx.materials);}ctx.render();}
   if(t.matches('[data-v5-family]')){const d=v5.dispatchEdit||={},families=new Set(d.families||[]);if(t.checked)families.add(t.value);else families.delete(t.value);d.families=[...families];ctx.render();}
   if(t.matches('[data-v5-catalog-search]')){v5.catalogSearch=t.value;ctx.render();}
 }));
 app.addEventListener('click',run(async(event,ctx)=>{
   const button=event.target.closest('[data-v5]');if(!button)return;event.preventDefault();const action=button.dataset.v5,I=v5.importer;
   if(action==='home'){await loadV5(ctx);ctx.state.view='dashboard';ctx.render();}
   if(action==='module'){const module=button.dataset.module;if(module==='dispatch'){await loadV5(ctx);ctx.state.view='dispatch';}else {if(!ctx.canCreateQuote()){ctx.state.view='projects';}else {ctx.newQuote(module);v5.importer=null;}}ctx.render();}
   if(action==='projects'){if(ctx.user){await ctx.loadProjects();ctx.state.view='projects';}else ctx.state.view='quote';ctx.render();}
   if(action==='new-group'){ctx.newQuote('');v5.importer=null;ctx.render();}
   if(action==='add-quote'){const group=ctx.projects.find(p=>(p.groupId||p.id)===button.dataset.id);ctx.newQuote('',group);v5.importer=null;ctx.render();}
   if(action==='open-quote'){ctx.openQuote(ctx.projects.find(p=>p.id===button.dataset.id));}
   if(action==='revisions'){v5.revisions=(await ctx.api(`/api/projects/${button.dataset.id}/revisions`)).revisions;ctx.render();}
   if(action==='open-revision'){ctx.openQuote(v5.revisions[Number(button.dataset.index)],true);}
   if(action==='new-revision'){ctx.state.readOnlyRevision=false;ctx.state.settings={...ctx.state.settings,calculationVersion:'6.0',perimeterTrim:10,neolithTrim:30,kerf:v5.config.defaultKerf??3};ctx.state.calculationSnapshot=null;ctx.state.loadedSignature=null;ctx.state.step=1;ctx.notify('Los cambios se guardarán como una revisión nueva; el cálculo anterior quedará en Historial.');}
   if(action==='settings'){await loadV5(ctx);ctx.state.view='v5-settings';ctx.render();}
   if(action==='catalog-manage'){await ctx.loadCatalog();ctx.state.view='v5-catalog';ctx.render();}
   if(action==='group-dispatch'){v55.dispatch={groupId:button.dataset.id};v5.dispatchEdit={groupId:button.dataset.id,families:freightFamilies(ctx.projects.filter(p=>(p.groupId||p.id)===button.dataset.id),ctx.materials)};await loadV5(ctx);ctx.state.view='dispatch';ctx.render();}
   if(action==='new-dispatch'){v5.dispatchEdit=null;ctx.render();}
   if(action==='edit-dispatch'){v5.dispatchEdit=structuredClone(v5.dispatches.find(d=>d.id===button.dataset.id));ctx.render();}
   if(action==='read-paste'){const next=freshImporter(ctx);next.text=I?.text||'';next.sheets=[{name:'Celdas pegadas',rows:parseText(next.text)}];next.config.mapping=suggestMapping(next.sheets[0].rows);v5.importer=next;ctx.render();}
   if(action==='suggest-mapping'){I.config.mapping=suggestMapping(I.config.transpose?transpose(currentRows(I)):currentRows(I),Number(I.config.headerRow));I.preview=null;ctx.render();}
   if(action==='save-template'){const name=window.prompt('Nombre para esta interpretación (solo columnas, símbolos y unidades):');if(name){I.templates[name]=structuredClone(I.config);localStorage.setItem('casa-v5-import-templates',JSON.stringify(I.templates));ctx.notify('Interpretación guardada en este navegador.');}}
   if(action==='preview-import'){I.preview=parseMappedRows(currentRows(I),{...I.config,sheetName:I.sheets[I.sheetIndex].name});ctx.render();}
   if(action==='confirm-import'){if(!I.preview||I.preview.issues.length)throw new Error('Corrige o excluye las filas indicadas antes de incorporar.');for(const p of I.preview.pieces){const error=ctx.pieceError(p);if(error)throw new Error(`Fila ${p.sourceRow}: ${error}`);if(!Number.isInteger(p.quantity)||p.quantity<1)throw new Error('Revisa las cantidades.');}ctx.state.pieces.push(...I.preview.pieces.map(p=>({...p,id:crypto.randomUUID()})));I.preview=null;ctx.notify('Bloque incorporado. Revisa y edita las piezas en el paso Revisión.');}
   if(action==='catalog-kind'){v5.productKind=button.dataset.kind;v5.productEdit=null;ctx.render();}
   if(action==='new-product'){v5.productEdit=null;ctx.render();}
   if(action==='edit-product'){v5.productEdit=structuredClone((v5.productKind==='board'?ctx.materials:v5.productKind==='accessory'?ctx.accessories:ctx.edges).find(p=>p.id===button.dataset.id));ctx.render();window.scrollTo({top:0,behavior:'smooth'});}
 }));
 app.addEventListener('submit',run(async(event,ctx)=>{
   const form=event.target,key=form.dataset.v5Form;if(!key)return;event.preventDefault();const data=Object.fromEntries(new FormData(form));
   if(key==='dispatch'){await ctx.api('/api/v5/dispatches',{method:'POST',body:{...v5.dispatchEdit,...data,families:new FormData(form).getAll('family')}});v5.dispatchEdit=null;await loadV5(ctx);ctx.notify('Despacho guardado con su valorización.');}
   if(key==='settings'){const freightRates=Object.fromEntries(Object.keys(familyNames).map(k=>[k,{base:Number(data['base_'+k]??v5.config.freightRates[k].base),perKm:Number(data['km_'+k]??v5.config.freightRates[k].perKm)}]));v5.config=await ctx.api('/api/v5/config',{method:'PATCH',body:{origin:{label:data.originLabel,address:data.originAddress,mapsUrl:data.originMaps},freightRates,defaultKerf:Number(data.defaultKerf),salesBasis:data.salesBasis}});ctx.notify('Configuración guardada.');}
   if(key==='commune'){const id=data.id||crypto.randomUUID(),communes=v5.config.communes.filter(c=>c.id!==id);communes.push({id,name:data.name,roadKm:Number(data.roadKm),source:data.source,verified:!!data.verified,verifiedAt:new Date().toISOString(),active:true});v5.config=await ctx.api('/api/v5/config',{method:'PATCH',body:{communes}});ctx.notify('Distancia guardada.');}
   if(key==='services'){const services=structuredClone(v5.config.services);for(const [name,value] of Object.entries(data)){const match=name.match(/^(.*)_(price|minPrice|purchasePrice)$/);if(match)services[match[1]][match[2]]=Number(value);}v5.config=await ctx.api('/api/v5/config',{method:'PATCH',body:{services}});ctx.notify('Valores de servicios guardados.');}
   if(key==='taxonomy'){const taxonomy=structuredClone(v5.config.taxonomy),id=data.id||crypto.randomUUID();let existing;const detach=nodes=>{for(let i=nodes.length-1;i>=0;i--){if(nodes[i].id===id){existing=nodes.splice(i,1)[0];}else detach(nodes[i].children||[]);}};detach(taxonomy);const node={...existing,id,name:data.name,family:data.family,active:data.active==='true'};if(data.parentId){const find=nodes=>nodes.flatMap(n=>[n,...(n.children?find(n.children):[])]).find(n=>n.id===data.parentId);const parent=find(taxonomy);if(!parent)throw new Error('El padre no puede ser la misma categoría ni una de sus subcategorías.');(parent.children||=[]).push(node);}else taxonomy.push(node);v5.config=await ctx.api('/api/v5/config',{method:'PATCH',body:{taxonomy}});ctx.notify('Categorías guardadas.');}
   if(key==='product'){const current=v5.productEdit,product={...current,...data};delete product.photo;for(const f of ['plateLength','plateWidth','thickness','netPrice','minPrice','purchasePrice','price','serviceRate','servicePurchasePrice','serviceMinPrice','perimeterTrim'])if(data[f]!==undefined)product[f]=Number(data[f]);product.active=data.active===undefined?current?.active:data.active==='true';product.grainRequired=data.grainRequired!=='false';product.stock=data.stock===''?null:Number(data.stock);const category=taxonomyPaths(v5.config.taxonomy).find(n=>n.id===data.taxonomyId);product.categoryId=category?.id||current?.categoryId||'otros-tableros';product.categoryName=category?.path||current?.categoryName||'Otros Tableros';const endpoint=current?`/api/admin/catalog/${v5.productKind}/${current.id}`:'/api/admin/catalog';await ctx.api(endpoint,{method:current?'PATCH':'POST',body:{productType:v5.productKind,product}});const photo=form.elements.photo?.files?.[0];if(photo)await ctx.uploadImage(product.sku,photo);await ctx.loadCatalog();v5.productEdit=null;ctx.notify('Nueva revisión del producto guardada.');}
 }));
}
