import {permitted,rolesOf,discountedLine} from './v5-domain.js';
import {internalUser} from './v51-domain.js';
import {freight55,shippingLines,validateComponents,dailyTarget,normalize} from './v55-domain.js';
export const v55={config:{routes:[],weights:{},productWeights:{},productivity:{},componentRules:{},resourceTemplates:{}},dispatches:[],operations:{tasks:[],entries:[],operators:[],rates:[],people:[]},report:[],dispatch:null,tab:'tasks',month:new Date().toISOString().slice(0,7),costs:null,operator:null,calculator:[],calculatorQuote:null,search:''};
const h=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=v=>v===null||v===undefined?'Pendiente':Number(v).toLocaleString('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
const qty=v=>Number(v||0).toLocaleString('es-CL',{maximumFractionDigits:3});
const opt=(v,n,s)=>`<option value="${h(v)}" ${String(v)===String(s)?'selected':''}>${h(n)}</option>`;
const field=(n,label,v='',type='text',extra='')=>`<label>${h(label)}<input name="${h(n)}" type="${type}" value="${h(v)}" ${extra}></label>`;
const button=(action,label,extra='')=>`<button type="button" class="secondary" data-v55="${action}" ${extra}>${h(label)}</button>`;
const select=(n,label,options,extra='')=>`<label>${h(label)}<select name="${n}" ${extra}>${options}</select></label>`;
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Santiago'});
const all=ctx=>[...ctx.materials,...ctx.edges,...ctx.accessories,...ctx.services];
const active=ctx=>all(ctx).filter(p=>p.active!==false);
const productOptions=(ctx,s,filter=()=>true)=>'<option value="">Seleccionar producto o servicio</option>'+active(ctx).filter(filter).map(p=>opt(p.id,`${p.sku} · ${p.name}`,s)).join('');
const serviceOptions=(ctx,s)=>ctx.services.filter(p=>p.active!==false).map(p=>opt(p.sku,p.sku+' · '+p.name,s)).join('');
const weightLabels={'tab-melamina':'Tableros de Melamina','tab-egr':'Tableros EGR Decor','tab-chinos':'Tableros Chinos','tab-otros':'Otros Tableros','tap-general':'Tapacantos','tap-egr':'Tapacantos EGR','tap-chinos':'Tapacantos Chinos','neo-06':'Neolith 6 mm','neo-12':'Neolith 12 mm','cuarzo-18':'Cuarzo 18 mm','granito-20':'Granito 20 mm',hinge:'Bisagra',guidePair:'Par de guías',liftSystem:'Sistema de elevación completo',otherSystem:'Otros sistemas Salice'};
const labels={boards:'Tableros',slabs:'Placas',installations:'Instalaciones',dispatch:'Despachos'};
const operationRole=ctx=>permitted(ctx.user,'tasks');
const costEdit=ctx=>rolesOf(ctx.user).includes('superadmin')||(rolesOf(ctx.user).includes('admin')&&permitted(ctx.user,'costs'));
export async function load55(ctx){
 v55.config=await ctx.api(internalUser(ctx.user)?'/api/v55/settings':'/api/v55/public-settings');
 if(ctx.user){v55.dispatches=(await ctx.api('/api/v55/dispatches')).dispatches;if(internalUser(ctx.user))v55.operations=await ctx.api('/api/v55/operations');}
 else {v55.dispatches=[];v55.operations={tasks:[],entries:[],operators:[],rates:[],people:[]};}
}
export function pricePreview55(result,state,ctx){
 const products=active(ctx),lines=(state.saleLines||[]).map(l=>{const p=products.find(p=>p.id===l.productId)||l.productSnapshot;if(!p){result.warnings.push('Selecciona el producto vigente de una línea adicional.');return {...l,net:0};}const price=p.netPrice??p.price;return {...l,sku:p.sku,name:p.name,unit:p.unit,productSnapshot:p,unitPrice:price,...discountedLine(price,l.quantity,permitted(ctx.user,'discount')?l.discount:0,p)};});
 const issues=validateComponents(lines,products,v55.config.componentRules);result.warnings.push(...issues);
 const p={...state,saleLines:lines,calculationSnapshot:result},delivery=state.delivery||{required:false};
 const quote=freight55(v55.config,delivery.communeId,shippingLines([p],{materials:ctx.materials,edgeBands:ctx.edges,accessories:ctx.accessories,services:ctx.services}),permitted(ctx.user,'discount')?delivery.discount:0,delivery.required);
 if(delivery.required&&quote.status!=='quoted')result.warnings.push(quote.reason);
 const s=result.summary;s.optimizationNet=s.net;s.additionalNet=Math.round(lines.reduce((n,l)=>n+l.net,0));s.shippingNet=quote.net||0;s.net=Math.round(s.optimizationNet+s.additionalNet+s.shippingNet);s.vat=Math.round(s.net*.19);s.total=s.net+s.vat;result.saleLines=lines;result.delivery={...delivery,quote};return result;
}
export function quoteExtras55(ctx){
 const s=ctx.state,readOnly=!ctx.canEditCurrent()||s.readOnlyRevision,lines=s.saleLines||[],d=s.delivery||{required:false};
 return `<section class="card v55-extras"><h3>Productos, servicios adicionales y despacho</h3><p>Material de tapacanto: 105%. Instalación: 100% de los metros colocados.</p>${readOnly?'':`<form data-v55-form="sale-line" class="v55-form-row">${select('productId','Producto o servicio',productOptions(ctx,''),'required')}${field('quantity','Cantidad',1,'number','min="0.001" step="0.001" required')}${permitted(ctx.user,'discount')?field('discount','Descuento %',0,'number','min="0" max="50" step="0.1"'):''}<button class="primary">Agregar</button></form>`}
 <div class="v5-scroll"><table><thead><tr><th>Referencia / producto</th><th>Cantidad</th><th>Unidad</th><th></th></tr></thead><tbody>${lines.map((l,i)=>{const p=all(ctx).find(p=>p.id===l.productId)||l.productSnapshot;return `<tr><td>${h(p?.sku)} · ${h(p?.name)}</td><td>${qty(l.quantity)}</td><td>${h(p?.unit)}</td><td>${readOnly?'':button('remove-line','Quitar',`data-index="${i}"`)}</td></tr>`;}).join('')||'<tr><td colspan="4">Sin adicionales.</td></tr>'}</tbody></table></div>
 ${lines.map(l=>{const p=active(ctx).find(p=>p.id===l.productId),rule=v55.config.componentRules?.[p?.sku]||p?.componentRule;return (rule?.required||[]).map(r=>`<p class="v55-note"><b>${h(p.sku)}:</b> ${h(r.label)} obligatorio · ${h(r.allowedSkus.join(', '))} · ${qty(l.quantity*r.quantity)} unidades.</p>`).join('')+(p?.compatibilityPending&&!rule?`<p class="alert">${h(p.sku)}: Administración debe definir sus complementos compatibles.</p>`:'');}).join('')}
 <fieldset ${readOnly?'disabled':''}><label class="checkbox-row"><input type="checkbox" data-v55-delivery="required" ${d.required?'checked':''}>El cliente requiere despacho</label>${d.required?`<div class="v5-grid">${select('deliveryCommune','Comuna habilitada','<option value="">Seleccionar comuna</option>'+v55.config.routes.filter(c=>c.active).map(c=>opt(c.id,c.name,d.communeId)).join(''),'data-v55-delivery="communeId"')}${field('deliveryStreet','Calle y número',d.street,'text','data-v55-delivery="street"')}${permitted(ctx.user,'discount')?field('deliveryDiscount','Descuento del despacho %',d.discount||0,'number','min="0" max="50" data-v55-delivery="discount"'):''}</div><p>El peso considera las placas completas utilizadas y los retazos. El precio suma 20% a la referencia y respeta el mínimo de la comuna.</p>`:'<p>Retiro en tienda · sin cobro de despacho.</p>'}</fieldset></section>`;
}
export function summaryExtras55(result){return `<section class="card"><h3>Adicionales y despacho</h3>${(result.saleLines||[]).map(l=>`<p>${h(l.sku)} · ${h(l.name)} · ${qty(l.quantity)} ${h(l.unit)} <b>${money(l.net)}</b></p>`).join('')}${result.delivery?.required?`<p>Despacho a ${h(result.delivery.quote.commune)} · ${qty(result.delivery.quote.weightKg)} kg <b>${money(result.delivery.quote.net)}</b></p>`:'<p>Retiro en tienda.</p>'}</section>`;}
function calendar(events){const [y,m]=v55.month.split('-').map(Number),offset=(new Date(Date.UTC(y,m-1,1)).getUTCDay()+6)%7;return `<div class="v51-calendar-scroll"><div class="v51-calendar">${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=>`<div class="v51-weekday">${d}</div>`).join('')}${Array.from({length:42},(_,i)=>{const d=new Date(Date.UTC(y,m-1,1-offset+i)),date=d.toISOString().slice(0,10);return `<div class="v51-day ${d.getUTCMonth()!==m-1?'outside':''}"><b>${d.getUTCDate()}</b>${events.filter(e=>(e.confirmedDate||e.proposedDate||e.date)===date&&e.status!=='cancelled').map(e=>`<button class="v51-event ${e.confirmedDate?'scheduled':'in_progress'}" data-v55="edit-dispatch" data-id="${h(e.id)}"><b>${h(e.projectName)}</b><span>${h(e.clientName)}</span><small>${e.confirmedDate?'Confirmado':'Sugerido'} · ${h(e.quote.commune)}</small></button>`).join('')}</div>`;}).join('')}</div></div>`;}
export function dispatch55View(ctx){
 const internal=internalUser(ctx.user),editable=permitted(ctx.user,'dispatch')||permitted(ctx.user,'suggestDispatch'),confirm=permitted(ctx.user,'dispatch'),d=v55.dispatch||{},groups=[...new Map(ctx.projects.map(p=>[p.groupId||p.id,p])).entries()];
 return `<div class="intro-row"><div><h2>${internal?'Calendario de despachos':'Cálculo de despachos'}</h2><p>${internal?'Comercial sugiere. Logística o Producción confirma y reasigna.':'Destinos habilitados y precio neto según los productos seleccionados.'}</p></div>${internal?button('new-dispatch','Nuevo despacho'):''}</div>${internal?`<section class="card"><label>Mes<input type="month" data-v55-month value="${v55.month}"></label>${calendar(v55.dispatches)}</section>`:''}
 ${editable?`<form class="card" data-v55-form="dispatch"><h3>${d.id?'Despacho seleccionado':'Proponer despacho'}</h3><div class="v5-grid">${select('groupId','Proyecto','<option value="">Seleccionar</option>'+groups.map(([id,p])=>opt(id,p.project.projectName+' · '+p.project.clientName,d.groupId)).join(''),'required')}${select('communeId','Comuna',v55.config.routes.filter(c=>c.active).map(c=>opt(c.id,c.name,d.communeId)).join(''))}${field('street','Calle y número',d.street,'text','required')}${field('proposedDate','Fecha sugerida',d.proposedDate||'','date','required')}${confirm?field('confirmedDate','Fecha confirmada',d.confirmedDate||'','date')+select('status','Estado',['proposed','scheduled','dispatched','delivered','cancelled'].map((k,i)=>opt(k,['Sugerido','Confirmado','En despacho','Entregado','Anulado'][i],d.status||'proposed')).join('')):''}${permitted(ctx.user,'discount')?field('discount','Descuento %',d.quote?.requestedDiscount||0,'number','min="0" max="50"'):''}${confirm?field('invoiceNumber','Factura',d.invoiceNumber)+field('invoiceDate','Fecha de factura',d.invoiceDate,'date'):''}${field('notes','Observaciones',d.notes)}</div>${d.quote?`<p>${money(d.quote.net)} neto · ${qty(d.quote.weightKg)} kg · ${h(d.quote.release||'Histórico')}</p><label class="checkbox-row"><input type="checkbox" name="requote">Revalorizar con las tarifas vigentes</label>`:''}<button class="primary">${confirm?'Guardar despacho':'Enviar sugerencia'}</button></form>`:d.id?`<section class="card"><h3>${h(d.projectName)}</h3><p>${h(d.street)} · ${h(d.quote.commune)}</p><p>Fecha sugerida: ${h(d.proposedDate||d.date)} · Confirmada: ${h(d.confirmedDate||'Pendiente')}</p><b>${money(d.quote.net)} neto</b></section>`:''}
 <section class="card"><h3>Calculadora de referencia</h3><form data-v55-form="calculator-add" class="v55-form-row">${select('productId','Producto',productOptions(ctx,''),'required')}${field('quantity','Cantidad',1,'number','min="0.001" step="0.001" required')}<button>Agregar</button></form><ul>${v55.calculator.map((l,i)=>`<li>${h(all(ctx).find(p=>p.id===l.productId)?.name)} · ${qty(l.quantity)} ${button('calculator-remove','Quitar',`data-index="${i}"`)}</li>`).join('')}</ul><form data-v55-form="calculator" class="v55-form-row">${select('communeId','Comuna',v55.config.routes.filter(c=>c.active).map(c=>opt(c.id,c.name,v55.calculatorQuote?.communeId)).join(''))}${permitted(ctx.user,'discount')?field('discount','Descuento %',0,'number','min="0" max="50"'):''}<button class="primary">Calcular despacho</button></form>${v55.calculatorQuote?`<p class="v55-total">${v55.calculatorQuote.status==='quoted'?`${money(v55.calculatorQuote.net)} neto · ${money(v55.calculatorQuote.total)} con IVA · ${qty(v55.calculatorQuote.weightKg)} kg`:h(v55.calculatorQuote.reason)}</p>`:''}</section>`;
}
export function operations55View(ctx){
 const o=v55.operations,c=v55.config,manager=operationRole(ctx),tabs=[['tasks','Tareas'],['operators','Operadores'],...(permitted(ctx.user,'reports')?[['report','Rendimiento y pagos']]:[]),...(permitted(ctx.user,'payRates')?[['rates','Tarifas por operador']]:[])];
 const heading=`<h2>Producción por operador</h2><p>42 horas semanales: lunes a jueves 08:00–17:30, colación 14:00–14:30; viernes 08:00–14:00.</p><div class="v5-actions">${tabs.map(([k,n])=>button('operations-tab',n,`data-tab="${k}"`)).join('')}</div>`;
 if(v55.tab==='operators'){const p=v55.operator||{};return heading+(manager?`<form class="card" data-v55-form="operator"><h3>Ficha del operador</h3><div class="v5-grid">${field('name','Nombre',p.name,'text','required')}${select('userId','Cuenta de acceso (opcional)','<option value="">Sin cuenta de acceso</option>'+o.people.map(u=>opt(u.id,u.name,p.userId)).join(''))}</div><p>Áreas de trabajo</p>${Object.entries(labels).map(([k,n])=>`<label class="checkbox-row"><input type="checkbox" name="areas" value="${k}" ${p.areas?.includes(k)?'checked':''}>${n}</label>`).join('')}<button class="primary">Guardar ficha</button>${button('new-operator','Nueva ficha')}</form>`:'')+`<section class="card"><h3>Operadores</h3>${o.operators.map(p=>`<p><b>${h(p.name)}</b> · ${p.areas.map(a=>labels[a]).join(', ')} ${manager?button('edit-operator','Editar',`data-id="${p.id}"`):''}</p>`).join('')}</section>`;}
 if(v55.tab==='rates')return heading+`<form class="card" data-v55-form="rate"><h3>Nueva tarifa y vigencia</h3><div class="v5-grid">${select('operatorId','Operador',o.operators.map(p=>opt(p.id,p.name,'')).join(''))}${select('serviceSku','Tipo de tarea',serviceOptions(ctx,''))}${select('mode','Modalidad',opt('unit','Por unidad producida','unit')+opt('hour','Por hora','unit')+opt('mixed','Mixta: unidad + hora','unit'))}${field('unitRate','Pago por unidad',0,'number','min="0" required')}${field('hourRate','Pago por hora',0,'number','min="0" required')}${field('effectiveDate','Vigente desde',today(),'date','required')}</div><p>La nueva tarifa se aplica al validar futuros registros. Los pagos ya registrados conservan su tarifa.</p><button class="primary">Guardar tarifa</button></form><section class="card"><h3>Tarifas registradas</h3><div class="v5-scroll"><table><thead><tr><th>Operador</th><th>Tarea</th><th>Modalidad</th><th>Unidad</th><th>Hora</th><th>Vigencia</th></tr></thead><tbody>${o.rates.map(r=>`<tr><td>${h(o.operators.find(p=>p.id===r.operatorId)?.name)}</td><td>${h(r.serviceSku)}</td><td>${h({unit:'Unidad',hour:'Hora',mixed:'Mixta'}[r.mode])}</td><td>${money(r.unitRate)}</td><td>${money(r.hourRate)}</td><td>${h(r.effectiveDate)}</td></tr>`).join('')}</tbody></table></div></section>`;
 if(v55.tab==='report')return heading+`<section class="card"><form data-v55-form="report" class="v55-form-row">${field('from','Desde',v55.month+'-01','date')}${field('to','Hasta',today(),'date')}<button class="primary">Consultar</button>${button('export-report','Descargar CSV')}</form><div class="v5-scroll"><table><thead><tr><th>Operador</th><th>Tarea</th><th>Producción</th><th>Tiempo</th><th>Rendimiento</th><th>Pago registrado</th></tr></thead><tbody>${v55.report.map(r=>`<tr><td>${h(r.operator)}</td><td>${h(r.serviceSku)}</td><td>${qty(r.quantity)} ${h(r.unit)}</td><td>${qty(r.minutes/60)} h</td><td>${r.performancePercent===null?'Sin tiempo registrado':qty(r.performancePercent)+'%'}</td><td>${r.payTotal===undefined?'Acceso restringido':money(r.payTotal)}${r.missingRates?` · ${r.missingRates} sin tarifa`:''}</td></tr>`).join('')||'<tr><td colspan="6">Selecciona un período.</td></tr>'}</tbody></table></div></section>`;
 const projects=ctx.projects.filter(p=>['facturado_pagado','produccion','despacho'].includes(p.project.status));
 return heading+(manager?`<form class="card" data-v55-form="task"><h3>Asignar trabajo</h3><div class="v5-grid">${select('quoteId','Proyecto / cotización',projects.map(p=>opt(p.id,p.project.projectName+' · '+p.quoteName,'')).join(''))}${select('area','Área',Object.entries(labels).map(([k,n])=>opt(k,n,'boards')).join(''))}${select('operatorId','Operador',o.operators.filter(p=>p.active).map(p=>opt(p.id,p.name,'')).join(''))}${select('serviceSku','Tarea',serviceOptions(ctx,''))}${field('quantity','Cantidad objetivo',1,'number','min="0.001" step="0.001" required')}${field('startDate','Inicio',today(),'date','required')}${field('startTime','Hora de inicio','08:00','time','required')}${field('plannedMinutes','Minutos previstos (solo sin rendimiento definido)','','number','min="1"')}${field('notes','Observaciones')}</div><button class="primary">Asignar y calcular término</button></form>`:'')+`<section class="card"><h3>Trabajos asignados</h3><div class="v55-task-grid">${o.tasks.map(t=>{const production=o.entries.filter(e=>e.taskId===t.id&&e.validated).reduce((n,e)=>n+e.quantity,0);return `<article class="v55-task"><small>${h(labels[t.area])} · ${h(t.status)}</small><h4>${h(t.name)}</h4><p>${h(ctx.projects.find(p=>p.id===t.quoteId)?.project.projectName)} · <b>${h(t.operator)}</b></p><p>${qty(production)} / ${qty(t.quantity)} ${h(t.unit)}</p><progress max="${t.quantity}" value="${production}"></progress><p>Meta del día: ${qty(dailyTarget(c.productivity[t.serviceSku],t.startDate))} ${h(t.unit)}</p><p>Inicio ${h(t.startDate)} ${h(t.startTime)}<br>Término previsto ${h(t.plannedEndDate)} ${h(t.plannedEndTime)}<br>Término real ${h(t.actualEnd||'Pendiente')}</p>${manager&&t.status!=='completed'?`<form data-v55-form="entry" data-id="${t.id}"><div class="v5-grid">${field('date','Día',today(),'date','required')}${field('quantity','Producción validada','','number','min="0.001" step="0.001" required')}${field('minutes','Minutos efectivos','','number','min="0" max="540" required')}</div><button>Registrar y validar avance</button></form>`:''}${t.status!=='completed'&&(manager||t.assignedUserId===ctx.user.id)?button('complete-task','Cerrar mi tarea',`data-id="${t.id}" data-version="${t.version}"`):''}</article>`;}).join('')||'<p>Sin tareas asignadas.</p>'}</div></section>`;
}
export function parameters55View(ctx){const c=v55.config;if(!permitted(ctx.user,'settings'))return '<p>Solo Administración puede modificar estos parámetros.</p>';return `<h2>Parámetros V5.5</h2><form class="card" data-v55-form="routes"><h3>Comunas y tarifas por kg</h3><div class="v5-scroll"><table><thead><tr><th>Comuna</th><th>Tarifa neta/kg</th><th>Mínimo neto</th><th>Activa</th></tr></thead><tbody>${c.routes.map((r,i)=>`<tr><td>${h(r.name)}</td><td><input name="rate_${i}" type="number" min="0" step="any" value="${r.ratePerKg}" required></td><td><input name="minimum_${i}" type="number" min="${r.local?5000:15000}" value="${r.minimumNet}" required></td><td><input name="active_${i}" type="checkbox" ${r.active?'checked':''}></td></tr>`).join('')}</tbody></table></div><button class="primary">Guardar tarifas</button></form><form class="card" data-v55-form="new-route"><h3>Agregar comuna</h3><div class="v5-grid">${field('name','Nombre','','text','required')}${field('ratePerKg','Tarifa neta/kg','','number','step="any" min="0" required')}</div><button>Agregar comuna habilitada</button><p>Mínimo neto: $15.000 para nuevas comunas.</p></form>
 <form class="card" data-v55-form="weights"><h3>Pesos por familia</h3><div class="v5-grid">${Object.entries(c.weights).map(([k,v])=>field(k,(weightLabels[k]||k)+' · kg',v,'number','min="0" step="any" required')).join('')}</div><button>Guardar pesos</button></form><form class="card" data-v55-form="product-weight"><h3>Peso particular por referencia</h3><div class="v5-grid">${select('productId','Referencia',productOptions(ctx,''),'required')}${field('weight','Kg por unidad de venta','','number','min="0" step="any" required')}</div><button>Guardar peso</button><p>Otros sistemas Salice: 50 kg por sistema completo. Sus accesorios separados requieren peso propio.</p><p>${Object.entries(c.productWeights).map(([k,v])=>h(k)+': '+qty(v)+' kg').join(' · ')||'Sin excepciones.'}</p></form>
 <form class="card" data-v55-form="productivity"><h3>Rendimientos por operador</h3><p>El día base son 9 horas productivas. El viernes se calcula con 6 horas.</p><div class="v5-scroll"><table><thead><tr><th>Servicio</th><th>Producción</th><th>Unidad</th><th>Período</th></tr></thead><tbody>${Object.entries(c.productivity).map(([k,p])=>`<tr><td>${h(ctx.services.find(s=>s.sku===k&&s.active!==false)?.name||k)}</td><td><input name="quantity_${k}" value="${p.quantity}" type="number" min="0.001" step="any" required></td><td>${h(p.unit)}</td><td><select name="period_${k}">${[['minute','Minuto'],['hour','Hora'],['day','Día de 9 horas']].map(([v,n])=>opt(v,n,p.period)).join('')}</select></td></tr>`).join('')}</tbody></table></div><button>Guardar rendimientos</button></form>
 <form class="card" data-v55-form="components"><h3>Relaciones y complementos Salice</h3><p>Define grupos de referencias compatibles. Cada grupo obligatorio se satisface con una de sus alternativas.</p><div class="v5-grid">${select('productId','Producto principal',productOptions(ctx,'',p=>p.productType==='accessory'),'required')}${field('label','Nombre del complemento (ej. base titanio)','','text','required')}${field('skus','Códigos compatibles separados por coma','','text','required')}${field('quantity','Cantidad por producto',1,'number','min="0.001" step="any" required')}${select('kind','Condición',opt('required','Obligatorio','required')+opt('optional','Opcional','required'))}</div><button>Agregar grupo de complementos</button></form>`;}
export function costs55View(ctx){const c=v55.costs;if(!c)return '<p>Selecciona un proyecto.</p>';const editable=!c.group&&permitted(ctx.user,'resources'),monetary=!c.group&&costEdit(ctx);return `<h2>${c.group?'Costos consolidados del proyecto':'Costos de la cotización'}</h2><p>${h(c.projectName||ctx.projects.find(p=>p.id===c.quoteId)?.project.projectName)}</p>${!c.group&&permitted(ctx.user,'costs')?button('group-costs','Ver consolidado del proyecto',`data-id="${c.groupId}"`):''}${c.actualCost!==undefined?`<div class="v5-kpis">${[['Planificado',c.plannedCost],['Costo registrado',c.actualCost],['Mano de obra',c.laborCost],['Venta neta',c.netRevenue],['Saldo sobre costos registrados',c.margin]].map(([n,v])=>`<article><span>${n}</span><strong>${money(v)}</strong></article>`).join('')}</div>`:''}<p class="alert">${c.complete?'Costos de las líneas informadas completos. Verifica que estén todos los insumos del proyecto.':'Informe provisional: faltan costos o recursos por registrar.'} ${h((c.missingCosts||[]).join(', '))}</p>
 <form class="card" data-v55-form="costs"><div class="v5-scroll"><table><thead><tr><th>Servicio / recurso</th><th>Tipo</th><th>Unidad</th><th>Previsto</th><th>Real</th>${monetary?'<th>Costo unitario</th>':''}</tr></thead><tbody>${c.lines.map((l,i)=>`<tr><td>${h(l.serviceSku)}<br>${h(l.name)}</td><td>${h({input:'Insumo',asset:'Uso de activo',external:'Servicio externo',expense:'Gasto'}[l.kind])}</td><td>${h(l.unit)}</td><td><input name="planned_${i}" type="number" min="0" step="any" value="${l.plannedQuantity}" ${editable?'':'disabled'}></td><td><input name="actual_${i}" type="number" min="0" step="any" value="${l.actualQuantity}" ${editable?'':'disabled'}></td>${monetary?`<td><input name="cost_${i}" type="number" min="0" step="any" value="${l.unitCost??''}" placeholder="Pendiente"></td>`:''}</tr>`).join('')}</tbody></table></div>${editable||monetary?'<button class="primary">Guardar consumos y costos</button>':''}${button('export-costs','Descargar reporte CSV')}</form>
 ${editable?`<form class="card" data-v55-form="resource"><h3>Agregar insumo, activo o gasto</h3><div class="v5-grid">${select('serviceSku','Servicio',serviceOptions(ctx,''))}${field('name','Recurso','','text','required')}${select('kind','Tipo',['input','asset','external','expense'].map((v,i)=>opt(v,['Insumo','Uso de activo','Servicio externo','Gasto'][i],'input')).join(''))}${field('unit','Unidad (kg, hora, día, gl…)','unidad')}${field('plannedQuantity','Cantidad prevista',0,'number','min="0" step="any"')}${field('actualQuantity','Cantidad real',0,'number','min="0" step="any"')}${monetary?field('unitCost','Costo unitario (vacío si pendiente)','','number','min="0" step="any"'):''}</div><p>Los activos se costean por su uso. La mano de obra proviene de la producción validada y no debe volver a cargarse aquí.</p><button>Agregar recurso</button></form><form class="card" data-v55-form="template"><h3>Plantilla de insumos del servicio</h3>${select('serviceSku','Servicio',serviceOptions(ctx,''))}<button name="action" value="apply">Aplicar plantilla</button>${permitted(ctx.user,'settings')?'<button name="action" value="save">Guardar estas líneas como plantilla del servicio</button>':''}</form>`:''}`;}
export function permissions55View(ctx){if(!rolesOf(ctx.user).includes('superadmin'))return '';return `<section class="card"><h3>Permisos específicos de Administradores</h3><p>La configuración de operadores y tarifas es independiente de la creación de cuentas de acceso.</p>${(ctx.users||[]).filter(u=>u.roles.includes('admin')&&!u.roles.includes('superadmin')).map(u=>`<form data-v55-form="permissions" data-id="${u.id}" class="v55-form-row"><b>${h(u.fullName)}</b><label class="checkbox-row"><input name="permissions" value="users" type="checkbox" ${u.permissions?.includes('users')?'checked':''}>Administrar usuarios</label><label class="checkbox-row"><input name="permissions" value="costs" type="checkbox" ${u.permissions?.includes('costs')?'checked':''}>Ver y configurar costos</label><button>Guardar permisos</button></form>`).join('')||'<p>No hay administradores delegados.</p>'}</section>`;}
function csvFile(name,rows){if(!rows.length)throw Error('No hay datos para exportar.');const keys=Object.keys(rows[0]),cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"',csv='\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(row=>row.map(cell).join(';')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
export function attach55(app,getContext){
 const run=fn=>async e=>{try{await fn(e,getContext());}catch(err){getContext().notify(err.message,'error');}};
 const refresh=async ctx=>{await ctx.loadProjects();await load55(getContext());ctx.render();};
 app.addEventListener('click',run(async(e,ctx)=>{const b=e.target.closest('[data-v55]');if(!b)return;e.preventDefault();const a=b.dataset.v55;
  if(['operations','parameters','dispatch'].includes(a)){await load55(ctx);ctx.state.view=a==='parameters'?'v55-parameters':a==='operations'?'v55-operations':'dispatch';}
  if(a==='new-sale'){ctx.newQuote('hardware');ctx.state.step=3;ctx.state.quoteName='Herrajes y servicios';ctx.state.view='quote';}
  if(a==='remove-line')ctx.state.saleLines.splice(Number(b.dataset.index),1);
  if(a==='calculator-remove')v55.calculator.splice(Number(b.dataset.index),1);
  if(a==='edit-dispatch'){v55.dispatch=structuredClone(v55.dispatches.find(d=>d.id===b.dataset.id));ctx.state.view='dispatch';}
  if(a==='new-dispatch')v55.dispatch=null;
  if(a==='operations-tab'){v55.tab=b.dataset.tab;}
  if(a==='edit-operator')v55.operator=structuredClone(v55.operations.operators.find(o=>o.id===b.dataset.id));
  if(a==='new-operator')v55.operator=null;
  if(a==='complete-task'){await ctx.api('/api/v55/tasks/'+b.dataset.id+'/complete',{method:'POST',body:{version:Number(b.dataset.version)}});await refresh(ctx);ctx.notify('Tarea cerrada. El proyecto avanza cuando termina toda su producción requerida.');}
  if(a==='costs'){v55.costs=await ctx.api('/api/v55/projects/'+b.dataset.id+'/costs');ctx.state.view='v55-costs';}
  if(a==='group-costs'){v55.costs=await ctx.api('/api/v55/groups/'+b.dataset.id+'/costs');ctx.state.view='v55-costs';}
  if(a==='export-report')csvFile('Produccion_por_operador.csv',v55.report.map(({projects,...r})=>({...r,projects:projects.join(', ')})));
  if(a==='export-costs')csvFile('Costos_proyecto.csv',[...(v55.costs.lines||[]).map(l=>({...l,actualLineCost:l.unitCost==null?'Pendiente':l.unitCost*l.actualQuantity})),...(v55.costs.laborCost!==undefined?[{name:'Mano de obra validada',actualLineCost:v55.costs.laborCost}]:[])]);
  ctx.render();
 }));
 app.addEventListener('change',run(async(e,ctx)=>{const t=e.target;if(t.matches('[data-v55-month]')){v55.month=t.value;ctx.render();}if(t.matches('[data-v55-delivery]')){if(!ctx.canEditCurrent())return;ctx.state.delivery||={required:false};ctx.state.delivery[t.dataset.v55Delivery]=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;ctx.render();}}));
 app.addEventListener('submit',run(async(e,ctx)=>{
  const form=e.target,key=form.dataset.v55Form;if(!key)return;e.preventDefault();const data=Object.fromEntries(new FormData(form)),post=(path,body)=>ctx.api(path,{method:'POST',body}),settings=async changes=>{v55.config=await ctx.api('/api/v55/settings',{method:'PATCH',body:{version:v55.config.version,...changes}});};
  if(key==='permissions'){const permissions=new FormData(form).getAll('permissions');await ctx.api('/api/v55/users/'+form.dataset.id+'/permissions',{method:'PATCH',body:{permissions}});const u=ctx.users.find(u=>u.id===form.dataset.id);u.permissions=permissions;ctx.notify('Permisos específicos actualizados.');}
  if(key==='sale-line'){if(!ctx.canEditCurrent())throw Error('Cotización de consulta.');ctx.state.saleLines||=[];ctx.state.saleLines.push({productId:data.productId,quantity:Number(data.quantity),discount:Number(data.discount||0)});}
  if(key==='calculator-add')v55.calculator.push({productId:data.productId,quantity:Number(data.quantity)});
  if(key==='calculator')v55.calculatorQuote=await post('/api/v55/freight-preview',{...data,lines:v55.calculator});
  if(key==='dispatch'){const result=await post('/api/v55/dispatches',{...v55.dispatch,...data,requote:!!data.requote});v55.dispatch=result.dispatch;await load55(ctx);}
  if(key==='operator'){await post('/api/v55/operators',{...v55.operator,...data,areas:new FormData(form).getAll('areas')});v55.operator=null;await load55(ctx);}
  if(key==='rate'){await post('/api/v55/pay-rates',data);await load55(ctx);}
  if(key==='task'){await post('/api/v55/tasks',data);await refresh(ctx);}
  if(key==='entry'){await post('/api/v55/entries',{...data,taskId:form.dataset.id});await load55(ctx);}
  if(key==='report')v55.report=(await ctx.api('/api/v55/production-report?'+new URLSearchParams(data))).rows;
  if(key==='routes')await settings({routes:v55.config.routes.map((r,i)=>({...r,ratePerKg:Number(data['rate_'+i]),minimumNet:Number(data['minimum_'+i]),active:!!data['active_'+i]}))});
  if(key==='new-route')await settings({routes:[...v55.config.routes,{id:normalize(data.name).replace(/[^a-z0-9]+/g,'-'),name:data.name,ratePerKg:Number(data.ratePerKg),minimumNet:15000,local:false,active:true}]});
  if(key==='weights')await settings({weights:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,Number(v)]))});
  if(key==='product-weight'){const p=active(ctx).find(p=>p.id===data.productId);await settings({productWeights:{...v55.config.productWeights,[p.sku]:Number(data.weight)}});}
  if(key==='productivity')await settings({productivity:Object.fromEntries(Object.entries(v55.config.productivity).map(([sku,p])=>[sku,{...p,quantity:Number(data['quantity_'+sku]),period:data['period_'+sku]}]))});
  if(key==='components'){const p=active(ctx).find(p=>p.id===data.productId),rules=structuredClone(v55.config.componentRules),rule=rules[p.sku]||structuredClone(p.componentRule)||{required:[],optional:[]};rule[data.kind]||=[];rule[data.kind]=rule[data.kind].filter(r=>r.label!==data.label);rule[data.kind].push({label:data.label,allowedSkus:data.skus.split(',').map(s=>s.trim()).filter(Boolean),quantity:Number(data.quantity)});rules[p.sku]=rule;await settings({componentRules:rules});}
  if(['resource','costs','template'].includes(key)){
   const c=v55.costs;let lines=structuredClone(c.lines);
   if(key==='resource')lines.push({...data,id:crypto.randomUUID(),unitCost:data.unitCost===''||data.unitCost===undefined?null:Number(data.unitCost),plannedQuantity:Number(data.plannedQuantity),actualQuantity:Number(data.actualQuantity)});
   if(key==='costs')lines=lines.map((l,i)=>({...l,plannedQuantity:data['planned_'+i]===undefined?l.plannedQuantity:Number(data['planned_'+i]),actualQuantity:data['actual_'+i]===undefined?l.actualQuantity:Number(data['actual_'+i]),unitCost:data['cost_'+i]===undefined?l.unitCost:data['cost_'+i]===''?null:Number(data['cost_'+i])}));
   if(key==='template'&&e.submitter.value==='save'){await settings({resourceTemplates:{...v55.config.resourceTemplates,[data.serviceSku]:lines.filter(l=>l.serviceSku===data.serviceSku).map(l=>({...l,id:undefined,actualQuantity:0}))}});ctx.notify('Plantilla guardada.');ctx.render();return;}
   if(key==='template')lines.push(...(v55.config.resourceTemplates[data.serviceSku]||[]).map(l=>({...l,id:crypto.randomUUID()})));
   await post('/api/v55/projects/'+c.quoteId+'/costs',{version:c.version,lines});v55.costs=await ctx.api('/api/v55/projects/'+c.quoteId+'/costs');
  }
  ctx.render();
 }));
}
